num1=int(input())
num2=int(input())
print(f"Sum of numbers are {num1+num2},substarction of numbers are {num1-num2}, Multiplication of numbers are {num1*num2},Division of numbers {num1/num2}")
print(f"power of number{num1**num2}")
#print(a+b)
#print(a-b)
#print(a*b)
#print(a/b)
#print(a%b)
#print(a**b)
#print(a//b)